import os

ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_DAYS = 7

CORS_ORIGINS = ["http://localhost:9998"]

COOKIE_DOMAIN = "localhost"
COOKIE_PATH = "/"
COOKIE_HTTPONLY = True
COOKIE_SECURE = True
COOKIE_SAMESITE = "lax"

MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT", "storage:9000")
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY")
MINIO_BUCKET_NAME = os.getenv("MINIO_BUCKET_NAME", "matcha")
MINIO_SECURE = False

ALLOWED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".gif"}
MAX_FILE_SIZE = 5 * 1024 * 1024
MAX_IMAGE_DIMENSIONS = (2000, 2000)
MAX_UPLOAD_FILES = 5

JWT_ALGORITHM = "HS256"
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")

EMAIL_VERIFICATION_REDIRECT_URL = os.getenv("EMAIL_VERIFICATION_REDIRECT_URL")
FRONT_BASE_URL = os.getenv("FRONT_BASE_URL")
