/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */

export interface BlockedUserSummary {
  username: string;
  first_name: string;
  last_name: string;
  profile_picture?: string | null;
  blocked_at: string;
}
