/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */

export interface ChatMessageCreate {
  /**
     * @minLength 1
     * @maxLength 2000
     */
  body: string;
}
