/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */

export interface ChatMessageResponse {
  id: number;
  body: string;
  created_at: string;
  read_at?: string | null;
  is_mine: boolean;
  sender_username: string;
}
