/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */
import type { SocialUserSummary } from './socialUserSummary';

export interface DateProposalResponse {
  id: number;
  status: string;
  scheduled_at: string;
  location_label?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  note?: string | null;
  is_mine: boolean;
  peer: SocialUserSummary;
  created_at: string;
  updated_at: string;
  responded_at?: string | null;
}
