/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */

export interface DateProposalCreate {
  username: string;
  scheduled_at: string;
  location_label?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  note?: string | null;
}
