/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */

export type Gender = typeof Gender[keyof typeof Gender];


export const Gender = {
  Male: 'Male',
  Female: 'Female',
} as const;
