/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */

export interface GeocodeRequest {
  /**
     * @minLength 2
     * @maxLength 128
     */
  query: string;
}
