/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */
import type { SortBy } from './sortBy';
import type { SortOrder } from './sortOrder';

export type GetSuggestionsApiUsersSuggestionsGetParams = {
sort_by?: SortBy;
order?: SortOrder | null;
min_age?: number | null;
max_age?: number | null;
max_distance_km?: number | null;
min_fame?: number | null;
max_fame?: number | null;
tags?: string | null;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
