/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationActor } from './notificationActor';
import type { NotificationResponsePayload } from './notificationResponsePayload';

export interface NotificationResponse {
  id: number;
  type: string;
  payload?: NotificationResponsePayload;
  read_at?: string | null;
  created_at: string;
  actor: NotificationActor;
}
