/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */

export interface SignInData {
  login: string;
  /** @minLength 8 */
  password: string;
}
