/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */

export interface SocialUserSummary {
  username: string;
  first_name: string;
  last_name: string;
  profile_picture?: string | null;
  fame_rating?: number;
  viewed_at?: string | null;
  liked_at?: string | null;
  is_online?: boolean;
  last_seen_at?: string | null;
}
