/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */

export type SortBy = typeof SortBy[keyof typeof SortBy];


export const SortBy = {
  distance: 'distance',
  age: 'age',
  fame: 'fame',
  common_tags: 'common_tags',
} as const;
