/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */
import type { SuggestedProfile } from './suggestedProfile';

export interface SuggestionListResponse {
  results: SuggestedProfile[];
  total: number;
  limit: number;
  offset: number;
}
