/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */

export interface SuggestedProfile {
  username: string;
  first_name: string;
  last_name: string;
  age: number;
  bio?: string | null;
  fame_rating?: number;
  profile_picture?: string | null;
  interests?: string[];
  common_interests?: string[];
  common_interest_count?: number;
  distance_km?: number | null;
  location_label?: string | null;
}
