/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */
import type { Gender } from './gender';

export interface UserUpdate {
  first_name?: string | null;
  last_name?: string | null;
  email?: string | null;
  bio?: string | null;
  gender?: Gender | null;
  sexual_preference?: Gender | null;
  interests?: string[] | null;
  images?: string[] | null;
  profile_picture?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  location_label?: string | null;
}
