/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */
import type { Gender } from './gender';

export interface UserPut {
  first_name: string;
  last_name: string;
  email: string;
  /**
     * @minLength 10
     * @maxLength 255
     */
  bio: string;
  gender: Gender;
  sexual_preference: Gender;
  interests?: string[] | null;
  images?: string[] | null;
  profile_picture?: string | null;
  latitude: number;
  longitude: number;
  location_label?: string | null;
  username: string;
}
