/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */
import type { Gender } from './gender';

export interface UserPut {
  bio?: string | null;
  gender?: Gender | null;
  sexual_preference?: string | null;
  interests?: string[] | null;
  images?: string[] | null;
  profile_picture?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  username: string;
  email: string;
  first_name: string;
  last_name: string;
}
