/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Matcha API
 * API for Matcha dating application
 * OpenAPI spec version: 1.0.0
 */
import type { UserImage } from './userImage';

export interface UserProfileResponse {
  id: number;
  email?: string | null;
  username: string;
  first_name: string;
  last_name: string;
  gender?: string | null;
  bio?: string | null;
  sexual_preference?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  location_label?: string | null;
  is_verified: boolean;
  is_profile_completed: boolean;
  fame_rating?: number;
  images?: UserImage[];
  interests?: string[];
  profile_picture?: string | null;
  age?: number | null;
  is_liked_by_viewer?: boolean;
  has_liked_viewer?: boolean;
  is_connected?: boolean;
  is_blocked?: boolean;
  is_online?: boolean;
  last_seen_at?: string | null;
}
