export const COMMON_PASSWORDS = new Set(
  [
    "password",
    "password1",
    "password123",
    "123456",
    "12345678",
    "123456789",
    "qwerty",
    "abc123",
    "monkey",
    "dragon",
    "master",
    "letmein",
    "login",
    "welcome",
    "admin",
    "passw0rd",
    "hello",
    "freedom",
    "whatever",
    "trustno1",
    "starwars",
    "football",
    "baseball",
    "iloveyou",
    "sunshine",
    "princess",
    "ashley",
    "bailey",
    "shadow",
    "superman",
    "batman",
    "charlie",
    "donald",
    "michael",
    "jennifer",
    "jordan",
    "hunter",
    "ranger",
    "buster",
    "thomas",
    "robert",
    "daniel",
    "matthew",
    "andrew",
    "joshua",
    "jessica",
    "amanda",
    "nicole",
    "matcha",
    "love",
    "secret",
    "access",
    "flower",
    "summer",
    "winter",
    "spring",
    "autumn",
    "computer",
    "internet",
    "google",
    "apple",
    "microsoft",
    "changeme",
    "default",
    "test",
    "testing",
    "guest",
    "user",
    "root",
    "administrator",
  ].map((word) => word.toLowerCase())
);

export function containsDictionaryWord(password: string): boolean {
  const lowered = password.toLowerCase();
  if (COMMON_PASSWORDS.has(lowered)) {
    return true;
  }

  const tokens = password.match(/[a-zA-Z]+/g) ?? [];
  return tokens.some((token) => COMMON_PASSWORDS.has(token.toLowerCase()));
}
