version: "3.8"

services:
  app:
    container_name: app
    build: .
    ports:
      - 7001:7001
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: matcha_db
    image: postgres:16
    env_file:
      - .env
    restart: always
    ports:
      - 5436:5432
    volumes:
      - match_db:/var/lib/postgresql/data
  storage:
    image: minio/minio:latest
    container_name: storage
    ports:
      - 9001:9000
      - 9090:9090
    command: server /data --console-address ":9090"
    volumes:
      - storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}

volumes:
  match_db:
  storage:
