version: '3.3'

services:
  app:
    container_name: app
    build: .
    ports:
      - 9000:9000
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: matcha_db
    image: postgres:16
    env_file:
      - .env
    restart: always
    ports:
      - 5431:5432
    volumes:
      - match_db:/var/lib/postgresql/data
  my-adminer:
    image: adminer:latest
    container_name: my-adminer
    ports:
      - 9090:8080
    depends_on:
      - db


volumes:
  match_db:
